/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import napakalaki.BadConsequence;

/**
 *
 * @author ixjosemi
 */
public class BadConsequenceView extends javax.swing.JPanel {

    private BadConsequence badconsequenceModel;
    
    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
    }
    
    public void setBadConsequence (BadConsequence bc){
        
        badconsequenceModel = bc;
        
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textLabel = new javax.swing.JLabel();
        levelsLabel = new javax.swing.JLabel();
        levels = new javax.swing.JTextField();
        death = new javax.swing.JTextField();
        deathLabel = new javax.swing.JLabel();
        nVisibleTreasures = new javax.swing.JTextField();
        nVisibleLabel = new javax.swing.JLabel();
        nHiddenLabel = new javax.swing.JLabel();
        nHiddenTreasures = new javax.swing.JTextField();
        specificVisibleTreasures = new javax.swing.JTextField();
        specificHiddenTreasures = new javax.swing.JTextField();
        specificVisibleLabel = new javax.swing.JLabel();
        specificHiddenLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        textLabel1 = new javax.swing.JLabel();
        levelsLabel1 = new javax.swing.JLabel();
        levels1 = new javax.swing.JTextField();
        death1 = new javax.swing.JTextField();
        deathLabel1 = new javax.swing.JLabel();
        nVisibleTreasures1 = new javax.swing.JTextField();
        nVisibleLabel1 = new javax.swing.JLabel();
        nHiddenLabel1 = new javax.swing.JLabel();
        nHiddenTreasures1 = new javax.swing.JTextField();
        specificVisibleTreasures1 = new javax.swing.JTextField();
        specificHiddenTreasures1 = new javax.swing.JTextField();
        specificVisibleLabel1 = new javax.swing.JLabel();
        specificHiddenLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        text1 = new javax.swing.JTextArea();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mal Rollo"));
        jPanel1.setToolTipText("");

        textLabel.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        textLabel.setText("Descripcion");
        textLabel.setToolTipText("");

        levelsLabel.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        levelsLabel.setText("Niveles Perdidos");
        levelsLabel.setToolTipText("");

        levels.setEditable(false);
        levels.setText("niveles");

        death.setEditable(false);
        death.setText("muerte");
        death.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deathActionPerformed(evt);
            }
        });

        deathLabel.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        deathLabel.setText("¿Te Mata?");
        deathLabel.setToolTipText("");

        nVisibleTreasures.setEditable(false);
        nVisibleTreasures.setText("nVisible");
        nVisibleTreasures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nVisibleTreasuresActionPerformed(evt);
            }
        });

        nVisibleLabel.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        nVisibleLabel.setText("Tesoros Visibles");
        nVisibleLabel.setToolTipText("");

        nHiddenLabel.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        nHiddenLabel.setText("Tesoros Ocultos");
        nHiddenLabel.setToolTipText("");

        nHiddenTreasures.setEditable(false);
        nHiddenTreasures.setText("nVisible");

        specificVisibleTreasures.setEditable(false);
        specificVisibleTreasures.setText("specificVisibleTreasures");

        specificHiddenTreasures.setEditable(false);
        specificHiddenTreasures.setText("specificHiddenTreasures");

        specificVisibleLabel.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        specificVisibleLabel.setText("Tipos de Tesoros Visibles");
        specificVisibleLabel.setToolTipText("");

        specificHiddenLabel.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        specificHiddenLabel.setText("Tipos de Tesoros Ocultos");
        specificHiddenLabel.setToolTipText("");

        text.setEditable(false);
        text.setColumns(1);
        text.setLineWrap(true);
        text.setRows(3);
        text.setTabSize(2);
        jScrollPane1.setViewportView(text);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(specificVisibleLabel)
                            .addComponent(specificHiddenLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(specificHiddenTreasures, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(levelsLabel)
                                    .addComponent(deathLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(death, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(levels, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nVisibleLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nHiddenLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nHiddenTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(nVisibleTreasures)))
                            .addComponent(specificVisibleTreasures, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(textLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelsLabel)
                    .addComponent(levels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nVisibleLabel)
                    .addComponent(nVisibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deathLabel)
                    .addComponent(death, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nHiddenLabel)
                    .addComponent(nHiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(specificVisibleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specificVisibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specificHiddenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specificHiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Mal Rollo"));
        jPanel2.setToolTipText("");

        textLabel1.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        textLabel1.setText("Description");
        textLabel1.setToolTipText("");

        levelsLabel1.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        levelsLabel1.setText("Lost levels");
        levelsLabel1.setToolTipText("");

        levels1.setEditable(false);
        levels1.setText("niveles");

        death1.setEditable(false);
        death1.setText("muerte");
        death1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                death1ActionPerformed(evt);
            }
        });

        deathLabel1.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        deathLabel1.setText("Does it kill you?");
        deathLabel1.setToolTipText("");

        nVisibleTreasures1.setEditable(false);
        nVisibleTreasures1.setText("nVisible");
        nVisibleTreasures1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nVisibleTreasures1ActionPerformed(evt);
            }
        });

        nVisibleLabel1.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        nVisibleLabel1.setText("Visible treasures");
        nVisibleLabel1.setToolTipText("");

        nHiddenLabel1.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        nHiddenLabel1.setText("Hidden treasures");
        nHiddenLabel1.setToolTipText("");

        nHiddenTreasures1.setEditable(false);
        nHiddenTreasures1.setText("nHidden");

        specificVisibleTreasures1.setEditable(false);
        specificVisibleTreasures1.setText("specificVisibleTreasures");

        specificHiddenTreasures1.setEditable(false);
        specificHiddenTreasures1.setText("specificHiddenTreasures");

        specificVisibleLabel1.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        specificVisibleLabel1.setText("Visible treasures:");
        specificVisibleLabel1.setToolTipText("");

        specificHiddenLabel1.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        specificHiddenLabel1.setText("Tipos de Tesoros Ocultos");
        specificHiddenLabel1.setToolTipText("");

        text1.setEditable(false);
        text1.setColumns(1);
        text1.setLineWrap(true);
        text1.setRows(3);
        text1.setTabSize(2);
        jScrollPane2.setViewportView(text1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(specificVisibleLabel1)
                            .addComponent(specificHiddenLabel1)
                            .addComponent(textLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(specificHiddenTreasures1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(levelsLabel1)
                                    .addComponent(deathLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(levels1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(death1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nVisibleLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nHiddenLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nHiddenTreasures1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(nVisibleTreasures1)))
                            .addComponent(specificVisibleTreasures1))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(textLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelsLabel1)
                    .addComponent(levels1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nVisibleLabel1)
                    .addComponent(nVisibleTreasures1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deathLabel1)
                    .addComponent(death1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nHiddenLabel1)
                    .addComponent(nHiddenTreasures1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(specificVisibleLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specificVisibleTreasures1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specificHiddenLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specificHiddenTreasures1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deathActionPerformed

    private void nVisibleTreasuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nVisibleTreasuresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nVisibleTreasuresActionPerformed

    private void death1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_death1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_death1ActionPerformed

    private void nVisibleTreasures1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nVisibleTreasures1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nVisibleTreasures1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField death;
    private javax.swing.JTextField death1;
    private javax.swing.JLabel deathLabel;
    private javax.swing.JLabel deathLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField levels;
    private javax.swing.JTextField levels1;
    private javax.swing.JLabel levelsLabel;
    private javax.swing.JLabel levelsLabel1;
    private javax.swing.JLabel nHiddenLabel;
    private javax.swing.JLabel nHiddenLabel1;
    private javax.swing.JTextField nHiddenTreasures;
    private javax.swing.JTextField nHiddenTreasures1;
    private javax.swing.JLabel nVisibleLabel;
    private javax.swing.JLabel nVisibleLabel1;
    private javax.swing.JTextField nVisibleTreasures;
    private javax.swing.JTextField nVisibleTreasures1;
    private javax.swing.JLabel specificHiddenLabel;
    private javax.swing.JLabel specificHiddenLabel1;
    private javax.swing.JTextField specificHiddenTreasures;
    private javax.swing.JTextField specificHiddenTreasures1;
    private javax.swing.JLabel specificVisibleLabel;
    private javax.swing.JLabel specificVisibleLabel1;
    private javax.swing.JTextField specificVisibleTreasures;
    private javax.swing.JTextField specificVisibleTreasures1;
    private javax.swing.JTextArea text;
    private javax.swing.JTextArea text1;
    private javax.swing.JLabel textLabel;
    private javax.swing.JLabel textLabel1;
    // End of variables declaration//GEN-END:variables
}
