/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import napakalaki.Napakalaki;
import napakalaki.Player;
import napakalaki.Treasure;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JPanel;


/**
 *
 * @author ixjosemi
 */

public class PlayerView extends javax.swing.JPanel {

    private Player playerModel;
    private Napakalaki napakalakiModel;
    private NapakalakiView napakalakiView;
    
    public PlayerView() {
        initComponents();
    }
    
    public void setPlayer(Player player){
        
        // se actualiza el atributo de referencia
        playerModel = player;
        
        // se actualiza la vista nombre del jugador
        this.LabelPlayerName.setText(playerModel.getName());
        this.LabelPlayerName.setForeground(Color.red);
        
        // Se actualiza la vista nivel del jugador
        this.LabelLevelPlayer.setText(Integer.toString(playerModel.getLevels()));

        // Se actualiza la vista de nivel de combate del jugador
        this.LabelCombatLevel.setText(Integer.toString(playerModel.getCombatLevel()));
        
        
        // Se actualiza la vista del enemigo del jugador
        this.LabelEnemy.setText(playerModel.getEnemy().getName());
        
        // Se actualiza la vista de si es sectario o no el jugador
        this.LabelCultist.setText(playerModel.IsCultist());
        
        
        // Actualizamos tesoros
        this.fillTreasurePanel(visibleTreasures,playerModel.getVisibleTreasures());
        this.fillTreasurePanel(hiddenTreasures,playerModel.getHiddenTreasures());
        
        repaint();
        revalidate();
    }
     
    private void fillTreasurePanel (JPanel aPanel, ArrayList<Treasure> aList) {
    
        // Se elimina la información antigua
        aPanel.removeAll();

        // Se recorre la lista de tesoros construyendo y añadiendo sus vistas
        // al panel
        for (Treasure t : aList) {
        
            TreasureView aTreasureView = new TreasureView();
            aTreasureView.setTreasure (t);
            aTreasureView.setVisible (true);
            aPanel.add (aTreasureView);
        }

        // Se fuerza la actualización visual del panel
        aPanel.repaint();
        aPanel.revalidate();
    }
    
    public void setNapakalaki(Napakalaki model) {

        napakalakiModel = model;
    }
    
    private ArrayList<Treasure> getSelectedTreasures(JPanel aPanel) {
        // Se recorren los tesoros que contiene el panel,
        // almacenando en un vector aquellos que están seleccionados.
        // Finalmente se devuelve dicho vector.
        TreasureView tv;
        
        ArrayList<Treasure> output = new ArrayList();
        
        for (Component c : aPanel.getComponents()) {
            
            tv = (TreasureView) c;
            
            if ( tv.isSelected() )
                output.add ( tv.getTreasure() );
            
        }
        
        return output;
    }

    public JButton getButtonDiscardTreasures() {
        return ButtonDiscardTreasures;
    }

    public JButton getButtonMakeVisible() {
        return ButtonMakeVisible;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonStealTreasure = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LabelName = new javax.swing.JLabel();
        LabelLevel = new javax.swing.JLabel();
        LabelCombatLvl = new javax.swing.JLabel();
        LabelEne = new javax.swing.JLabel();
        LabelCult = new javax.swing.JLabel();
        LabelPlayerName = new javax.swing.JLabel();
        LabelLevelPlayer = new javax.swing.JLabel();
        LabelCombatLevel = new javax.swing.JLabel();
        LabelEnemy = new javax.swing.JLabel();
        LabelCultist = new javax.swing.JLabel();
        visibleTreasures = new javax.swing.JPanel();
        hiddenTreasures = new javax.swing.JPanel();
        ButtonStealTreasure1 = new javax.swing.JButton();
        ButtonMakeVisible = new javax.swing.JButton();
        ButtonDiscardAllTreasures = new javax.swing.JButton();
        ButtonDiscardTreasures = new javax.swing.JButton();

        ButtonStealTreasure.setForeground(new java.awt.Color(255, 0, 0));
        ButtonStealTreasure.setText("Steal Treasure");
        ButtonStealTreasure.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ButtonStealTreasure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStealTreasureActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("PLAYER");
        jLabel1.setToolTipText("");

        LabelName.setText("Name:");

        LabelLevel.setText("Level:");

        LabelCombatLvl.setText("Combat level:");

        LabelEne.setText("Enemy:");

        LabelCult.setText("Cultist:");

        LabelPlayerName.setText("jLabel7");

        LabelLevelPlayer.setText("jLabel7");

        LabelCombatLevel.setText("jLabel7");

        LabelEnemy.setText("jLabel7");

        LabelCultist.setText("jLabel7");

        visibleTreasures.setBorder(javax.swing.BorderFactory.createTitledBorder("Tesoros Visibles"));

        hiddenTreasures.setBorder(javax.swing.BorderFactory.createTitledBorder("Tesoros ocultos"));

        ButtonStealTreasure1.setForeground(new java.awt.Color(0, 153, 153));
        ButtonStealTreasure1.setText("Steal Treasure");
        ButtonStealTreasure1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ButtonStealTreasure1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStealTreasure1ActionPerformed(evt);
            }
        });

        ButtonMakeVisible.setForeground(new java.awt.Color(0, 153, 153));
        ButtonMakeVisible.setText("Make Visible");
        ButtonMakeVisible.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ButtonMakeVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMakeVisibleActionPerformed(evt);
            }
        });

        ButtonDiscardAllTreasures.setForeground(new java.awt.Color(0, 153, 153));
        ButtonDiscardAllTreasures.setText("Discard All Treasures");
        ButtonDiscardAllTreasures.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ButtonDiscardAllTreasures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDiscardAllTreasuresActionPerformed(evt);
            }
        });

        ButtonDiscardTreasures.setForeground(new java.awt.Color(0, 153, 153));
        ButtonDiscardTreasures.setText("Discard Treasures");
        ButtonDiscardTreasures.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ButtonDiscardTreasures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDiscardTreasuresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelName)
                            .addComponent(LabelLevel)
                            .addComponent(LabelCombatLvl)
                            .addComponent(LabelEne)
                            .addComponent(LabelCult))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelCultist)
                            .addComponent(LabelEnemy)
                            .addComponent(LabelCombatLevel)
                            .addComponent(LabelLevelPlayer)
                            .addComponent(LabelPlayerName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(248, 248, 248))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonStealTreasure1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonDiscardTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonDiscardAllTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonMakeVisible, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hiddenTreasures, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(visibleTreasures, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ButtonDiscardTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonDiscardAllTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonMakeVisible, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addComponent(ButtonStealTreasure1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabelName)
                                    .addComponent(LabelPlayerName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabelLevel)
                                    .addComponent(LabelLevelPlayer))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabelCombatLvl)
                                    .addComponent(LabelCombatLevel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabelEne)
                                    .addComponent(LabelEnemy))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabelCult)
                                    .addComponent(LabelCultist))
                                .addGap(138, 138, 138))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(hiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(visibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))))
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonStealTreasureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStealTreasureActionPerformed
        napakalakiModel.getCurrentPlayer().stealTreasure();

        setPlayer(napakalakiModel.getCurrentPlayer());

        repaint();
    }//GEN-LAST:event_ButtonStealTreasureActionPerformed

    private void ButtonStealTreasure1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStealTreasure1ActionPerformed
        napakalakiModel.getCurrentPlayer().stealTreasure();

        setPlayer(napakalakiModel.getCurrentPlayer());

        repaint();
    }//GEN-LAST:event_ButtonStealTreasure1ActionPerformed

    private void ButtonMakeVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMakeVisibleActionPerformed
        ArrayList<Treasure> selHidden = getSelectedTreasures (hiddenTreasures);

        napakalakiModel.makeTreasuresVisible (selHidden);

        setPlayer (napakalakiModel.getCurrentPlayer());

        repaint();
    }//GEN-LAST:event_ButtonMakeVisibleActionPerformed

    private void ButtonDiscardAllTreasuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDiscardAllTreasuresActionPerformed
        napakalakiModel.getCurrentPlayer().discardAllTreasures();

        setPlayer(napakalakiModel.getCurrentPlayer());

        repaint();
    }//GEN-LAST:event_ButtonDiscardAllTreasuresActionPerformed

    private void ButtonDiscardTreasuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDiscardTreasuresActionPerformed
        ArrayList<Treasure> selVisible = getSelectedTreasures(visibleTreasures);
        napakalakiModel.discardVisibleTreasures(selVisible);

        ArrayList<Treasure> selHidden = getSelectedTreasures(hiddenTreasures);
        napakalakiModel.discardHiddenTreasures(selHidden);

        setPlayer(napakalakiModel.getCurrentPlayer());

        repaint();
    }//GEN-LAST:event_ButtonDiscardTreasuresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDiscardAllTreasures;
    private javax.swing.JButton ButtonDiscardTreasures;
    private javax.swing.JButton ButtonMakeVisible;
    private javax.swing.JButton ButtonStealTreasure;
    private javax.swing.JButton ButtonStealTreasure1;
    private javax.swing.JLabel LabelCombatLevel;
    private javax.swing.JLabel LabelCombatLvl;
    private javax.swing.JLabel LabelCult;
    private javax.swing.JLabel LabelCultist;
    private javax.swing.JLabel LabelEne;
    private javax.swing.JLabel LabelEnemy;
    private javax.swing.JLabel LabelLevel;
    private javax.swing.JLabel LabelLevelPlayer;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelPlayerName;
    private javax.swing.JPanel hiddenTreasures;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel visibleTreasures;
    // End of variables declaration//GEN-END:variables
}
